apache/madlib

src/ports/postgres/modules/recursive_partitioning/decision_tree.py_in
src/ports/postgres/modules/recursive_partitioning/decision_tree.sql_in
src/ports/postgres/modules/recursive_partitioning/random_forest.py_in
src/ports/postgres/modules/recursive_partitioning/test/decision_tree.sql_in
src/ports/postgres/modules/recursive_partitioning/test/random_forest.sql_in
src/ports/postgres/modules/utilities/utilities.py_in

This PR contains two separate but correlated pieces of work. 
The 1st commit is a bugfix to filter NULL values in the dependent column. 
The 2nd commit adds support for array columns as features in DT and RF.

Two DT/RF enhancements

---

doc/design/figures/wcc_example.pdf
doc/design/modules/graph.tex
doc/literature.bib
doc/mainpage.dox.in
src/ports/postgres/modules/graph/test/wcc.sql_in
src/ports/postgres/modules/graph/wcc.py_in
src/ports/postgres/modules/graph/wcc.sql_in

JIRA: MADLIB-1083
Add grouping support to weakly connected components. Make necessary
changes in the queries involved, docs, and install check. 
@orhankislal

Feature: Add grouping to weakly connected components

---

src/ports/postgres/modules/deep_learning/madlib_keras.py_in
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
src/ports/postgres/modules/deep_learning/test/keras_model_arch_table.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in

JIRA: MADLIB-1350
Add code to enable warm start by adding a new param named warm_start to
the fit function, and making other necessary validation and code
changes.
This commit also adds dev check for both warm start and
transfer learning. We replaced the existing transfer learning test with
a more deterministic test for the same by using iris (a more real world
dataset.)
Co-authored-by: Nikhil Kak <nkak@pivotal.io>
Co-authored-by: Orhan Kislal <okislal@pivotal.io>

DL: Enable warm start

---

src/ports/postgres/modules/kmeans/kmeans.sql_in
src/ports/postgres/modules/kmeans/test/kmeans.sql_in

Kmeans: Use squared dist norm2 as a default for silh functions

---

src/ports/postgres/modules/utilities/pivot.py_in
src/ports/postgres/modules/utilities/pivot.sql_in

Pivot: Use output_table instead of out_table

---

.github/pull_request_template.md

This template will help in creating all the PRs in the same format as per the doc: 
https://cwiki.apache.org/confluence/display/MADLIB/Contribution+Guidelines

Added a Pull Request Template

---

src/ports/postgres/modules/deep_learning/keras_model_arch_table.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras.py_in
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
src/ports/postgres/modules/deep_learning/predict_input_params.py_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_cifar.setup.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_evaluate.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_predict.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_predict_byom.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_transfer_learning.sql_in
src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in

JIRA: MADLIB-1387
This commit updates the evaluate and predict functions to support
individual models from fit_multiple outputs.

DL: Update evaluate and predict for multi model outputs

---

src/ports/postgres/modules/deep_learning/test/madlib_keras_transfer_learning.sql_in

DL: Fix transfer learning dev-check test

---

src/ports/postgres/modules/deep_learning/input_data_preprocessor.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in

This PR fixes the following bugs:
1. metrics_elapsed_time for fit multi model was not captured correctly in the info table
2. Drop leftover tables

DL: Fix bugs 

---

RELEASE_NOTES
deploy/DEB/postinst
deploy/postflight.sh
pom.xml
src/config/Version.yml
src/madpack/changelist_1.16_1.17.yaml
src/madpack/diff_udf.sql
src/madpack/madpack.py
src/madpack/upgrade_util.py
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in

Release117

---

src/madpack/changelist_1.16_1.17.0.yaml

Update changelist file name and remove incorrect entry

---

deploy/DEB/postinst
deploy/postflight.sh
pom.xml
src/config/Version.yml

Update version to 1.18.0-dev

---

src/madpack/changelist_1.17.0_1.18.0-dev.yaml
src/madpack/madpack.py
src/madpack/upgrade_util.py
src/madpack/utilities.py

Simplify upgrade

---

doc/mainpage.dox.in
src/config/Modules.yml
src/ports/postgres/modules/assoc_rules/assoc_rules.sql_in
src/ports/postgres/modules/dbscan/dbscan.py_in
src/ports/postgres/modules/dbscan/dbscan.sql_in
src/ports/postgres/modules/dbscan/test/dbscan.sql_in
src/ports/postgres/modules/dbscan/test/unit_tests/plpy_mock.py_in
src/ports/postgres/modules/dbscan/test/unit_tests/test_dbscan.py_in

This commit adds the DBSCAN module. It includes the brute force
implementation of DBSCAN as well as a prediction function. In
addition their associated tests and online documentation are
included.

DBSCAN: Add new module DBSCAN

---

doc/mainpage.dox.in
src/ports/postgres/modules/dbscan/dbscan.sql_in

This PR is for the new DBSCAN method for brute force and tree methods.

DBSCAN user docs

---

src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.sql_in

DL: Update user docs for load_custom_function

---

tool/docker/base/Dockerfile_postgres_10_Jenkins
tool/jenkins/jenkins_build.sh

Jenkins dockerfile had to be updated to include dbscan dependencies.
The new image requires a small change in the way we start the
docker as well.

Build: Fix Jenkins dockerfile and script

---

src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_custom_function.setup.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_custom_function.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_model_averaging_e2e.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection_e2e.sql_in

JIRA: MADLIB-1433
This commit adds support for custom metrics to DL functions.
Most of the additions depend on the commit that added the custom
loss functions.

DL: Add support for custom metrics

---

src/ports/postgres/modules/deep_learning/madlib_keras.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in

DL: Check for nan loss and metric

---

src/ports/postgres/modules/deep_learning/gpu_info_from_tf.py_in
src/ports/postgres/modules/deep_learning/madlib_keras.py_in
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
src/ports/postgres/modules/deep_learning/model_arch_info.py_in
src/ports/postgres/modules/deep_learning/test/keras_model_arch_table.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_cifar.setup.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_predict.sql_in
src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_automl.py_in
src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_model_selection_table.py_in

JIRA: MADLIB-1438
Remove keras dependency to use the keras from the tensorflow package.
Remove the channels first test since it only works on GPUs.

DL: Remove keras dependency

---

src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl_hyperband.py_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_automl.sql_in

JIRA: MADLIB-1456
For hyperband, the metrics_elapsed_time column was not cumulative. This commit
adds code to make it cumulative
Co-authored-by: Ekta Khanna <ekhanna@vmware.com>

DL: Fix hyperband metrics_elapsed_time calculation

---

src/ports/postgres/modules/deep_learning/madlib_keras_automl.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl_hyperband.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl_hyperopt.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_automl.sql_in

JIRA: MADLIB-1461
Add caching to automl interface

DL: Add caching to automl interface

---

LICENSE
licenses/third_party/_M_widen_init.txt
src/utils/libstdcxx-compatibility.cpp

LICENSE: Include full Copyright statements for _M_widen_init

---

src/ports/postgres/modules/deep_learning/madlib_keras.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_evaluate.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_multi_io.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_predict.sql_in
src/ports/postgres/modules/deep_learning/test/madlib_keras_predict_byom.sql_in
src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
src/ports/postgres/modules/utilities/utilities.sql_in

JIRA: MADLIB-1464
See individual commit messages for details

DL: Fix bugs when passing invalid input/output tables and other misc bugs

---

NOTICE
src/ports/postgres/modules/deep_learning/test/madlib_keras_fit_multiple.sql_in
src/ports/postgres/modules/utilities/debug.py_in
tool/jenkins/jenkins_build.sh
tool/jenkins/rat_check.sh

Changes for the newly created build job on cloudbees jenkins https://ci-builds.apache.org/job/Madlib/

Jenkins pr build

---

Jenkinsfile
tool/jenkins/jenkins_build.sh
tool/jenkins/rat_check.sh

Add Jenkinsfile

---

README.md

Update README with the link to new build job

---

Jenkinsfile

Jenkins: Add junit for test reporting

---

src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in

DL: Fix predict bug for the multi dependent single independent case

---

CMakeLists.txt
src/CMakeLists.txt
src/ports/postgres/dbconnector/NewDelete.cpp

Fix boost version bug in cmake < 3.15

---

src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.sql_in

DL: Remove AOcontrol from model selection functions

---

doc/mainpage.dox.in
src/ports/postgres/modules/dbscan/dbscan.sql_in
src/ports/postgres/modules/deep_learning/input_data_preprocessor.sql_in
src/ports/postgres/modules/deep_learning/keras_model_arch_table.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras.py_in
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_gpu_info.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.sql_in
src/ports/postgres/modules/utilities/minibatch_preprocessing.sql_in

DL: Various docs changes

---

src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.py_in
src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
src/ports/postgres/modules/utilities/utilities.py_in

DL: Check if the owner of the object table is a superuser

---

RELEASE_NOTES

Release notes for 1.18.0 based of public JIRAs

release notes for 1dot18dot0

---

src/ports/postgres/modules/deep_learning/test/madlib_keras_evaluate.sql_in

DL: Fix syntax errors in keras evaluate test

---

deploy/DEB/postinst
deploy/postflight.sh
pom.xml
src/config/Version.yml

Increment the version to 1.19.0-dev

---

tool/docker/base/Dockerfile_postgres_11_Jenkins
tool/docker/base/README.md
tool/jenkins/jenkins_build.sh

Build: Add new dockerfile for PG11 and updates the jenkins tests to use this new docker image

---

RELEASE_NOTES
deploy/DEB/postinst
deploy/postflight.sh
pom.xml
src/config/Version.yml
src/madpack/changelist_1.18.0_1.19.0.yaml
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/svm/svm.sql_in

Release: Update version numbers and add release notes

---

CMakeLists.txt
NOTICE
RELEASE_NOTES
deploy/CMakeLists.txt
deploy/Readme_OSX
deploy/link_madlib_folders.sh
src/ports/postgres/modules/dbscan/dbscan.sql_in

Release v1.19.0 rc2

---

RELEASE_NOTES
deploy/DEB/postinst
deploy/postflight.sh
pom.xml
src/config/Version.yml
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/svm/svm.sql_in

Co-authored-by: Bhuvnesh Chaudhary <bchaudhary@pivotal.io>

Update version to 1.20.0-dev and add release date

---

RELEASE_NOTES
deploy/DEB/postinst
deploy/postflight.sh
pom.xml
src/config/Version.yml
src/madpack/changelist_1.19.0_1.20.0.yaml
src/madpack/create_changelist.py
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/svm/svm.sql_in

Release 120 prep

---

RELEASE_NOTES
deploy/DEB/postinst
deploy/postflight.sh
pom.xml
src/config/Version.yml
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/svm/svm.sql_in
tool/jenkins/jenkins_build.sh

Update version number to 1.21.0-dev

---

doc/example/madlib_xgboost_example.sql

XGBoost: Fix documentation example

---

src/ports/postgres/modules/graph/apsp.py_in
src/ports/postgres/modules/graph/apsp.sql_in
src/ports/postgres/modules/graph/graph_utils.py_in
src/ports/postgres/modules/graph/sssp.py_in
src/ports/postgres/modules/graph/sssp.sql_in
src/ports/postgres/modules/graph/test/apsp.sql_in
src/ports/postgres/modules/graph/test/sssp.sql_in

JIRA: MADLIB-1506
This is a follow up commit for 8a24663ccf2ee76ef538c416ed505485b740ff04,
applying the same logic to add multi column vertex identification
support to SSSP, APSP, and their respective get path functions.

Graph: Add multi column support for SSSP and APSP

---

cmake/TestIfNoUTF8BOM.py

Fix TestIfNoUTF8BOM.py for newer versions of cmake

---

NOTICE

Update NOTICE for 2023

---

src/CMakeLists.txt
src/ports/greenplum/CMakeLists.txt
src/ports/postgres/CMakeLists.txt

Disable TestIfNoUTF8BOM.py for all platforms

---

RELEASE_NOTES
deploy/DEB/postinst
deploy/postflight.sh
pom.xml
src/config/Version.yml
src/madpack/changelist_1.20.0_1.21.0.yaml
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/svm/svm.sql_in

Build: Update version to 1.21.0 and add release notes

---

src/ports/postgres/modules/graph/sssp.py_in
src/ports/postgres/modules/graph/test/sssp.sql_in

SSSP: Drop temp views

---

RELEASE_NOTES
deploy/DEB/postinst
deploy/postflight.sh
pom.xml
src/config/Version.yml
src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
src/ports/postgres/modules/svm/svm.sql_in

Update version numbers to 1.22.0-dev

---

src/ports/postgres/modules/graph/wcc.sql_in

WCC: Update docs with warm start example
