- src/ports/postgres/modules/linalg/matrix_ops.py_in
JIRA: MADLIB-932
This commit contains fixes for following issues:
- 'inf' or 'infinity' was read by Python as a float value. This has
been fixed by checking for supported strings before checking for
float.
- matrix_inverse and matrix_pinv were not using out_args for output
column names.
- matrix_eigen did not accept an out_args parameter that determines the
output column names.
- Multiple methods did not provide a default value for out_args.
- All decomposition methods had incorrect usage for in_args and
out_args. These have been fixed with the output being sparse or
dense (determined by the fmt specifier in out_args).
> Matrix: Fix multiple input/output issues

- src/ports/postgres/modules/utilities/path.py_in
- src/ports/postgres/modules/utilities/test/path.sql_in
JIRA: MADLIB-1003
The various expressions in the partition_expr parameter are now
quoted and renamed. These expressions were not renamed earlier,
which led to an error when there were multiple expressions in the
parameter. Renaming them using ' AS ' fixes this issue.
This commit also includes an update to the install check, which
now includes multiple expressions in partition_expr.
> Path: Handling multiple expressions in partition_expr

- src/ports/postgres/modules/linalg/matrix_ops.py_in
- src/ports/postgres/modules/pca/pca.py_in
- src/ports/postgres/modules/pca/pca.sql_in
- src/ports/postgres/modules/pca/pca_project.py_in
- src/ports/postgres/modules/pca/pca_project.sql_in
- src/ports/postgres/modules/pca/test/pca.sql_in
- src/ports/postgres/modules/pca/test/pca_project.sql_in
JIRA: MADLIB-947
- PCA can now handle grouping columns. pca_train() with grouping_cols
parameter specified learns an independent model for each group in
the input table. New columns corresponding to the columns specified
in grouping_cols will be created in the output, mean and summary
tables.
- If pca_project() is called on an input table that has grouping_cols
in it, the pc_table used in the parameter list must be a PCA model
table that is learnt with grouping_cols. If the input table for
pca_project() has grouping columns but the pc_table used does not
support grouping_cols, or vice versa, there will be an error thrown.
- Another important new feature is that the 'row_id' column in the
input tables always had to be serially increasing, starting from 1. That
requirement is now relaxed …
> PCA: Add grouping support to PCA

- src/utils/MallocAllocator.hpp
The headerguard for MallocAllocator is defining a different macro than what it's testing for (seems to be an off-by-one on the keyboard). Fix the defined macro to match the check and filename.
> Fix headerguard for MallocAllocator

- src/ports/postgres/modules/recursive_partitioning/decision_tree.py_in
- src/ports/postgres/modules/recursive_partitioning/decision_tree.sql_in
- src/ports/postgres/modules/recursive_partitioning/test/decision_tree.sql_in
Reduce the defaults for max_depth to 7 and num_splits to 20 to ensure we
don't run out of memory when initializing tree for problems with many
features or with features with many categorical values.
> Decision Tree: Update defaults for max_depth, num_splits

- src/ports/postgres/modules/graph/test/wcc.sql_in
JIRA: MADLIB-1177
WCC install check sql file had madlib hard coded as the schema name.
This commit removes the schema name altogether, since install-check
anyway sets the schema name in the search path at the beginning.
Closes #199
> Bugfix: Hard coded schema name in WCC install check

- src/madpack/changelist_1.12_1.13.yaml
- src/madpack/upgrade_util.py
- src/ports/postgres/modules/convex/test/mlp.sql_in
JIRA: MADLIB-1197
Additional Author: Nandish Jayaram <njayaram@apache.org>
- 1.13 Upgrade does not drop the kNN help functions even though their
return types are changed. This commit adds the missing functions to the
changelist and alters the upgrade_util.py_in so that functions without
arguments can be dropped.
- Some assert thresholds are too strict for MLP in IC. This commit relaxes
those thresholds.
Closes #224
> 1.13 Upgrade and MLP IC fix

- src/ports/postgres/modules/convex/mlp_igd.py_in
- src/ports/postgres/modules/convex/utils_regularization.py_in
- src/ports/postgres/modules/elastic_net/elastic_net.py_in
- src/ports/postgres/modules/elastic_net/elastic_net_utils.py_in
- src/ports/postgres/modules/pca/pca.py_in
- src/ports/postgres/modules/stats/cox_prop_hazards.py_in
- src/ports/postgres/modules/utilities/mean_std_dev_calculator.py_in
- src/ports/postgres/modules/utilities/minibatch_preprocessing.py_in
- src/ports/postgres/modules/utilities/minibatch_preprocessing.sql_in
- src/ports/postgres/modules/utilities/test/minibatch_preprocessing.sql_in
- src/ports/postgres/modules/utilities/test/unit_tests/plpy_mock.py_in
- src/ports/postgres/modules/utilities/test/unit_tests/test_minibatch_preprocessing.py_in
- src/ports/postgres/modules/utilities/test/unit_tests/test_utilities.py_in
- src/ports/postgres/modules/utilities/utilities.py_in
- src/ports/postgres/modules/utilities/validate_args.py_in
JIRA: MADLIB-1200
MiniBatch Preprocessor is a utility function to pre-process the input
data for use with models that support mini-batching as an optimization.
The main purpose of the function is to prepare the training data for minibatching algorithms.
1. If the dependent variable is boolean or text, perform one hot encoding.  N/A for numeric.
2. Typecast independent variable to double precision[]
2. Based on the buffer size, group all the dependent and independent variables in a single tuple representative of the buffer.
Notes
1. Ignore null values in independent and dependent variables
2. Standardize the input before packing it.
Other changes:
1. Removed __ from public methods in utils_regularization.py
Renamed __utils_ind_var_scales and __utils_ind_var_scales_grouping
so that we can …
> MiniBatch Pre-Processor: Add new module minibatch_preprocessing

- src/modules/convex/mlp_igd.cpp
- src/modules/convex/task/mlp.hpp
- src/ports/postgres/modules/convex/mlp.sql_in
- src/ports/postgres/modules/convex/mlp_igd.py_in
- src/ports/postgres/modules/convex/test/mlp.sql_in
JIRA:MADLIB-1222
MLP currently automatically encodes categorical variables for
classification but does not allow already encoded arrays for dependent
variables in mlp_classification. This commit lets users have an already
encoded array for the dependent variable and train a model.
> MLP: Allow one-hot encoded dependent var for classification

- src/ports/postgres/modules/recursive_partitioning/test/random_forest.sql_in
JIRA: MADLIB-1225
The variable importance computation involves randomization inherently.
So it is hard to reproduce this error consistently. This commit comments
out the assert for now (the failure rate was around 4.3%, when tested over
600 runs).
Closes #258
> RF: Comment out assert in flaky install check query

- src/madpack/madpack.py
- src/madpack/upgrade_util.py
- src/madpack/utilities.py
We now write all the necessary sql into one file, and run it once in a
single session. The database's rollback will be useful to bring it back
to original state in case of a failure.
Co-authored-by: Rahul Iyer <riyer@apache.org>
Co-authored-by: Orhan Kislal <okislal@pivotal.io>
> Madpack: Make install, reinstall and upgrade atomic

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
In our experiments on a multi host gpdb cluster, we noticed that using CPU and compiling the model everytime caused the fit query to fail during the validate code with the error `Dst tensor is not
initialized`. Adding GPU and caching the compiled model fixed this issue.
1. Add GPU support to the evaluate code called by the fit function.
2. The evaluate code previously compiled the model for each row in the validation table.
This was unnecessary and takes more resources in terms of time and memory. This commit avoids this by using SD to cache the compiled model.
3. Also refactored the code by creating a function to get the rows per segment
> DL: Add GPU support for evaluate

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1343
Performance improvements
1. Using SD to cache the model and set the weights only once for the
first row for each segment. This also meant that we had to clear the SD
for the last row for each segment.
2. We replaced `PythonFunctionBodyOnly` with
`PythonFunctionBodyOnlyNoSchema` in the internal keras predict sql.
Using `PythonFunctionBodyOnly` made the query much slower because it
added the overhead of executing the schema query for every row in the
test table. We don't really need to know the schema name for the
internal UDF so now we use `PythonFunctionBodyOnlyNoSchema` instead.
Additionally:
1. Replace the use of predict_classes and proba with predict since non
sequential models do not support predict_classes.
2. Modify the internal keras predict query to not join the …
> DL: Improve performance for predict

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/predict_input_params.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras.sql_in
JIRA: MADLIB-1347
This PR adds the 'model_arch' column to the model data table so that
predict and evaluate can directly get the model_arch from the model data
table instead of the model arch table.
We have made changes to the predict code in this commit but the changes
for evaluate will be done in a future PR.
Co-authored-by: Nikhil Kak <nkak@pivotal.io>
> DL: Add model_arch column to model data table

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_serializer.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
This PR aims to improve the way metrics are handled. 
1. We add support for various metrics
2. We validate to make sure only a single metric is passed
3. We add support for metrics_compute_frequency for training data
4. We remove metric and loss computation from fit transition
> DL: Add support for reporting various metrics in fit/evaluate

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1349, MADLIB-1338
Add a new column named `metrics_type` that captures the metric name
(if) specified in the compile params. This commit also fixes the
model_size reported, it was reporting the wrong size.
There were a few comments in MADLIB-1338 after the corresponding PR was
merged to master. Some of those comments are addressed in this PR since
they are related code, and minor changes.
1. Ensure compile_params cannot be NULL.
2. Update some info messages.
3. Use the @MinWarning decorator to suppress notices.
4. Ensure training_metrics_final and validation_metrics_final are NULL
if the compile params did not have any metric specified.
Co-authored-by: Jingyi Mei <jmei@pivotal.io>
>  DL: Update content of the model summary table

- src/madpack/madpack.py
- src/ports/postgres/modules/deep_learning/keras_model_arch_table.py_in
- src/ports/postgres/modules/deep_learning/keras_model_arch_table.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_serializer.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/predict_input_params.py_in
- src/ports/postgres/modules/deep_learning/test/keras_model_arch_table.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
DL: Add model_weights, name and desc to the model arch table.
JIRA: MADLIB-1348
This commit adds three optional params to the model arch interface.
1. model weights in bytea format
2. name
3. description
The model_weights param will allow the user to load pre trained weights
to enable transfer learning
1. Remove image count from the serialized model weights that get stored
in the model output table. This image count was unnecessary and also
caused inconsistency in the model weights format in model_arch and
keras fit model out table.
2. Use bytea to store/read model weights. This includes the input param
and output col type. Here is why
a. we found that in python, using double precision[] or real[] was
almost double in size as compared to bytea.
b. It also helps keep the internal state of …
> DL: Enable transfer learning

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1356
Currently for postgres, we create one keras session in
fit/evaluate/predict and keep it open for all the iterations and then
close it at the end.  We did a few experiments and found out that if we
create 1 keras session per iteration , it performs slightly better.
So this commit modifies the code to make pg behave the same as gpdb(1
session per iteration) in fit_transition, eval_transition and
internal_predict functions.
We also changed set_keras_session to use a device_name to be consistent
with other keras operations.
This commit also fixes the following bug: 
If gpus are available on the
host but the user passed in 0 for the gpus_per_host param, we still end
up using gpu memory. This is because in the madlib_keras.fit UDF we call
model.get_weights() to initialize the …
> DL: Create one keras session per iteration for pg in fit and evaluate 

- src/ports/postgres/modules/deep_learning/input_data_preprocessor.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/model_arch_info.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1371 , MADLIB-1359
Previously a user would have to train a deep learning model in madlib
and only then they could use that model to predict.
This commit adds a new function called `madlib_keras_predict_byom` which allows the
user to run prediction on their own model which doesn't have to be
trained on madlib.
* Refactored the code to reuse the logic between predict and
predict_byom
* user doc changes
Co-authored-by: Nandish Jayaram <njayaram@apache.org>
Co-authored-by: Orhan Kislal <okislal@apache.org>
> DL: Add function for predict bring your own model

- doc/src/sql.yy
This shouldn't break anything for old versions of bison (2.4+),
but will enable current versions of bison to be able to build madlib.
Current versions will still give some deprecation warnings, but no
errors.
(See [reductionista/bison-update](https://github.com/reductionista/madlib/tree/bison-update) branch for more aggressive update that will get
rid of the warnings, but drops support for pre-3.3)
> Quick fix for bison issue

- deploy/gppkg/gppkg_spec.yml.in
- src/CMakeLists.txt
Currently, the madlib gppkg that gets generated only contains the MADlib
version.  For GPDB6, we want to add a suffix to the MADlib version i.e.
madlib-1.16-gp6-rhel6-x86_64.gppkg will now be madlib-1.16+1-gp6-rhel6-x86_64.gppkg.
If the CMAKE option is passed in as `+build+1`, the gppkg artifact
should be named `madlib-1.17+build+1-gp6-rhel6-x86_64.gppkg`
Co-authored-by: Orhan Kislal <okislal@apache.org>
> Build: Add cmake variable for gppkg filename

- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1375
This commit adds a new function to generate the model selection table.
It generates such tables as the naive combinations of the three input
lists of parameter choices. This utility also validates and
de-duplicates the inputs.
Co-authored-by: Domino Valdano domino@apache.org
> Add generate mst table utility.

- tool/docker/base/Dockerfile_postgres_10_Jenkins
With recent jenkins failure for DL module, keras(2.2.5) broke
the api such that the tf module within keras backend is not
available directly by:
```
from keras import backend as K
with K.tf. ....
```
This PR updates the Dockerfile to install keras v2.2.4
> DL Infra: Update jenkins to install keras 2.2.4

- src/ports/postgres/modules/deep_learning/input_data_preprocessor.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/test/input_data_preprocessor.sql_in
JIRA: MADLIB-1378
Currently, `training_preprocessor_dl` and `validation_preprocessor_dl`
doesn't guarantee even distribution of the data among segments,
especially when the number of buffers is not much larger than the number
of segments. This commit adds support to the preprocessor so that it
always distributes the data as evenly as possible among the segments.
> DL: Add support in preprocessor to evenly distribute data for GPDB

- src/ports/postgres/modules/deep_learning/input_data_preprocessor.py_in
- src/ports/postgres/modules/deep_learning/input_data_preprocessor.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/test/input_data_preprocessor.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_cifar.setup.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
- src/ports/postgres/modules/utilities/minibatch_validation.py_in
JIRA: MADLIB-1345
We noticed an improvement in performance when passing independent and
dependent var as bytea instead of REAL[], SMALLINT[]. This commit makes
the necessary updates to use bytea in both columns.
Co-authored-by: Ekta Khanna  <ekhanna@pivotal.io>
> DL: Update training_preprocessor_dl to use bytea

- tool/jenkins/jenkins_build.sh
Our jenkins build fails when creating the tmp dir `/tmp`. This commit
adds a -p flag to the mkdir command to avoid this failure.
> Use -p while creating tmp dir for jenkins build.

- src/modules/linalg/metric.cpp
- src/ports/postgres/modules/kmeans/kmeans.py_in
- src/ports/postgres/modules/kmeans/kmeans.sql_in
- src/ports/postgres/modules/kmeans/test/kmeans.sql_in
- src/ports/postgres/modules/linalg/linalg.sql_in
- src/ports/postgres/modules/utilities/utilities.py_in
Adds function for computing silhouette score for every input data point.
```
simple_silhouette_points(rel_source,   -- data points
output_table  -- output containing (pid, centroid, score) for each point
pid,          -- point id
expr_point,   -- column name or expression that defines points
centroids,    -- centroids 
fn_dist       -- distance function
)
```
> Kmeans: simplified silhouette per point for k-means

- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
JIRA: MADLIB-1345
Passing huge model weights as a param to `internal_keras_predict()` for
each row in the table slows the performance of overall `madlib_keras_predict()`.
With this PR, the model weights will be passed in as a param only for the
very first row(min(ctid)) fetched on each segment and NULL for the rest.
With this change, we see `~4x` performance boost in the execution time
of the existing `madlib_kerase_predict()`.
> DL: Improve performance for madlib_keras_predict()

- tool/docker/base/Dockerfile_postgres_10_Jenkins
The latest version of tensorflow (2.0 as of this commit) is not compatible with the version of keras that we install i.e. 2.2.4.
This is the error we get
```
AttributeError: 'module' object has no attribute 'get_default_graph'
```
This commit installs a compatible version of tensorflow i.e. 1.14.
> DL: Update jenkins to install tensorflow 1.14.

- src/ports/postgres/modules/deep_learning/input_data_preprocessor.sql_in
Since we changed to bytea for packed dep and indep vars, needed to update the users docs to correspond.
For weird and unknown doxygen issues, @kaknikhil & I learned that 
```
DROP AGGREGATE IF EXISTS MADLIB_SCHEMA.agg_array_concat(anyarray);
CREATE AGGREGATE MADLIB_SCHEMA.agg_array_concat(anyarray) (
SFUNC = array_cat,
PREFUNC = array_cat,
STYPE = anyarray
);
```
works but 
```
DROP AGGREGATE IF EXISTS MADLIB_SCHEMA.agg_array_concat(anyarray);
CREATE AGGREGATE MADLIB_SCHEMA.agg_array_concat(anyarray) (
SFUNC = array_cat,
STYPE = anyarray,
PREFUNC = array_cat
);
```
results in a blank page being published.  This is not root cause, but the docs do compile by doing this.
> updated DL preprocessor docs for bytea

- src/ports/postgres/modules/deep_learning/input_data_preprocessor.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_cifar.setup.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_iris.setup.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_averaging_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_predict.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
- src/ports/postgres/modules/utilities/minibatch_validation.py_in
This PR fixes the following issues:
1. Fix crash in `madlib_keras_fit_multiple_model()` for user inputed one-hot encoded data(y)
2. Avoid GPU memory issues caused due to long lasting processes left from queries creating TEMP tables.
3. Avoid creating unnecessary multiple slices (which might lead to GPU memory issues) using distribution_key instead of gp_segment_id
4. Fix `madlib_keras_predict()` not to display the following warning: 
```
WARNING:  column "attributes_shape" does not exist
CONTEXT:  PL/Python function "madlib_keras_predict"
madlib_keras_predict
----------------------
```
5. Add E2E test for `madlib_keras_fit()` and `madlib_keras_fit_multiple_model()`.
Note: Some tests in `madlib_keras_model_selection_e2e.sql_in` can be uncommented once PR #451 is merged
> DL: Fix miscellaneous bugs

- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_iris.setup.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_transfer_learning.sql_in
JIRA: MADLIB-1389
This commit enables transfer learning for multi-model training by
copying the weights from the model arch table.
> DL: Enable transfer learning for multi model training

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/model_arch_info.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_predict.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_model_selection_table.py_in
Prior to this PR, `model_id` was referenced with names like
`model_arch_id` and `model_arch_table_id`. This commit ensures, that its
consistent throughout using `model_id`.
> DL: Make model_id naming consistent

- doc/mainpage.dox.in
- src/ports/postgres/modules/deep_learning/gpu_info_from_tf.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_gpu_info.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_gpu_info.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_gpu_info.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_gpu_info.py_in
JIRA: MADLIB-1390
This commit adds a new helper function to query the gpu configuration of
the cluster. The purpose of this function is to list the state of the
cluster w.r.t GPUs, however it is configured. This will be useful in
case of supporting asymmetric clusters.
Also takes in a source param which can be one of 'tensorflow' or
'nvidia'. Defaults to 'tensorflow'.
Example for gpdb
```
List the state of the cluster, however it is configured:
SELECT * FROM madlib.gpu_configuration();
gpu_descr     | hostname
-----------------+-------------------------
NVIDIA Tesla P100 | host1
NVIDIA Tesla P100 | host1
Super Duper GPU   | host2
Super Duper GPU   | host2
(4 rows)
```
Example for postgres
```
select * from madlib.gpu_configuration();
hostname | gpu_descr
---------+-----------
localhost | …
```
> DL: Add new helper function for gpu_configuration

- src/ports/postgres/modules/lda/lda.sql_in
- src/ports/postgres/modules/utilities/text_utilities.sql_in
JIRA: MADLIB-1395
Set client_min_messages to 'error' for all lda related functions to
silence postgres notice messages.
> LDA: Turn off create table notices

- doc/mainpage.dox.in
- src/ports/postgres/modules/deep_learning/input_data_preprocessor.sql_in
- src/ports/postgres/modules/deep_learning/keras_model_arch_table.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_gpu_info.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_averaging_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_predict.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_predict_byom.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1394
This commit updates the madlib_keras_predict and associated functions to
use use_gpus parameter like the rest of the keras functions.
Current implementation does not allow for asymmetric gpu configurations.
> DL: Add asymmetric cluster check for predict

- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/test/input_data_preprocessor.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_predict.sql_in
Prior to this PR, due to the missing `SELECT`, call to
`trap_error()` would always return 1, irrespective of whether
the execution of the query would error out or not. This commit
updates such tests to pass in an executable SQL query.
This PR also fixes a bug in predict that was missed due to
the missing `SELECT` in the query param passed to trap_error().
> DL: Update tests calling trap_error()

- src/ports/postgres/modules/deep_learning/input_data_preprocessor.py_in
Prior to this PR, on GPDB6, running the preprocessor on a large
dataset would crash GPDB with the following error:
`ERROR:  DTX RollbackAndReleaseCurrentSubTransaction dispatch failed`
This was only an issue on GPDB6 not on GPDB5/Postgres. This PR fixes the issue on GPDB6.
> DL: Fix failure on GPDB6 for preprocessor

- NOTICE
- src/ports/postgres/modules/deep_learning/test/madlib_keras_transfer_learning.sql_in
A dev-check test for transfer learning was failing every once in a while.
This helps smooth out the learning curve, making the test be more
predictable... much less likely to fail due to a random fluctuation.
Co-authored-by: Orhan Kislal <okislal@apache.org>
> Decrease the learning rate for transfer learning test

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1405
For versions >=GPDB6, previously, for queries called with the initial
weights value passed in, the query plan for it would have create custom
plans with weights embedded in the plan itself.  This meant that the
query plan size would also include the size of these weights, bloating
it up to hit the 1GB limit when dispatching the query plan to segments,
leading to OOM for large weights.
In GPDB, for PREPARE plans, there is a threshold of 5 attempts to create
custom plans(constant folding the passed in params) for execution and
then it uses a generic plan(not constant folding the passed in params)
for all the subsequent executions.  Therefore, to avoid GPDB6 from
creating custom plans when passing in weights, the queries(with weights)
is executed with DUMMY weights for 5 …
> DL: Avoid constant folding of weights in GPDB6 plan

- CMakeLists.txt
**Jira**: [MADLIB-1410](https://issues.apache.org/jira/browse/MADLIB-1410)
Implement a check that `-mno-sse2` option is available for the chosen GNU CXX compiler. This [is a platform-specific option](https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/i386-and-x86-64-Options.html) and should not be set on machines with architectures that do not support it.
This requires a new CMake module `CheckCXXCompilerFlag`. It [is available in CMake 2.8.4](https://cmake.org/cmake/help/v2.8.4/cmake.html), which is the lowest currently supported CMake version.
An extra CMake variable, `SSE_DISABLE_OPTIONS`, is introduced to hold options required for GNU CXX compilers that support SSE-specific options.
The implemented mechanism is just one of multiple possible implementations. For example, one could check the …
> Build: Check -mno-sse2 is available for GNU CXX

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
The `get_initial_weights()` function in `madlib_keras.py_in` is shared by both `madlib_keras_fit()` and `madlib_keras_fit_multiple()`.  But until now the code was
not updated to support fit_multiple().  When called with warm-start=TRUE, this was causing improper initialization of weights for small datasets, and out-of-memory errors for larger datasets.
This adds a parameter to this internal helper function, that is used to select the appropriate `mst_key` while querying the previous model output table for the weights belonging to that model.
> Fix fit_multiple() warm start

- src/ports/postgres/modules/summary/Summarizer.py_in
JIRA: MADLIB-1413
Summarizer used python defaults for setting up the optional parameters.
If the user passes a NULL, these values get overwritten. This commit
fixes this issue by moving the defaults inside the code.
> Summary: Fix defaults when the user passes NULL

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_serializer.py_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
1. Based on our experiments, we noticed that at the end of each hop, fit
multiple would start using a lot of memory (from 80 GB to ~ 140 GB on
the master host of our gcp cluster) and we attributed that memory spike
to the final function.
Removing the final function brought down the memory to around 30-40 GB
and also made the places10 query 3 times faster
2. Improvements to "serializing weights with image count"
> DL: Remove fit final multiple and improve serialization of image_count+weights

- src/ports/postgres/modules/graph/apsp.py_in
- src/ports/postgres/modules/graph/bfs.py_in
- src/ports/postgres/modules/graph/bfs.sql_in
- src/ports/postgres/modules/graph/measures.py_in
- src/ports/postgres/modules/graph/measures.sql_in
- src/ports/postgres/modules/graph/sssp.py_in
- src/ports/postgres/modules/graph/test/apsp.sql_in
- src/ports/postgres/modules/graph/test/bfs.sql_in
- src/ports/postgres/modules/graph/test/hits.sql_in
- src/ports/postgres/modules/graph/test/measures.sql_in
- src/ports/postgres/modules/graph/test/pagerank.sql_in
- src/ports/postgres/modules/graph/test/sssp.sql_in
- src/ports/postgres/modules/graph/test/wcc.sql_in
- src/ports/postgres/modules/utilities/validate_args.py_in
JIRA: MADLIB-1415
SSSP, APSP and BFS output tables had entries for unconnected vertices,
denoted by a NULL parent column. This commit filters these rows to
clean up the output tables.
> Graph: Filter out infinite paths

- src/ports/postgres/modules/convex/mlp_igd.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
- src/ports/postgres/modules/utilities/control.py_in
- src/ports/postgres/modules/utilities/test/unit_tests/test_control.py_in
- src/ports/postgres/modules/utilities/test/unit_tests/test_utilities.py_in
- src/ports/postgres/modules/utilities/utilities.py_in
JIRA: MADLIB-1414
This PR reverts the previous commit for avoiding constant folding of weights in GPDB6 plans. Instead, there is a GUC introduced in GPDB6(`plan_cache_mode`) that allows controlling whether to choose generic plan(not constant folding the passed in params)/custom plans(constant folding the passed in params) for execution. This PR uses this GUC for choosing generic plan for GPDB6 execution.
This PR also fixes a bug in the way `class_values` were populated in fit multiple's summary table; it would fail when the class_values had `NULL` values in the array.
NOTE: For the prior versions of GPDB6, where this GUC doesn't exist, the DL queries will fail with `memory alloc` error for those versions.
> DL: Set plan_cache_mode to choose generic plan when passing weights for GPDB6

- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_predict.sql_in
This commit removes 2 problematic tests that we decided weren't worth including in the DL dev-check tests.
One of these tests was checking to make sure that `madlib_keras_fit()` fails when you pass `use_gpus=True`. And the other does the same for `madlib_keras_predict()`.  This wasn't a problem originally because we usually run dev-check only on Jenkins or other docker images where there are no GPU's. But as we continue to improve our pre-release testing process, we'd like to have dev-check be able to pass on GPU-enabled test platforms as well. So these tests are no longer appropriate.
> DL: Remove tests for no GPU hardware

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_serializer.py_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1418
Previously the model state would consist of the image count and the serialized
model weights but there was no need to include the serialized model weights as
part of the state except for the last row for that segment. We were only using
that state to get the image count and ignored the model weights, so serializing
the model weights for every row was a waste to time and resources.
This commit changes that pattern so that for all rows except the last row, the
state would be just the image count only.
> DL: Don't include weights as part of state except for the last row.

- src/ports/greenplum/dbconnector/dbconnector.hpp
- src/ports/postgres/dbconnector/Allocator_impl.hpp
This reverts commit d62e5516bc6741beee18678da1b9b3e6cc95cdcf.
GPDB6 updated the finalize_windowaggregate function to use
MemoryContextContainsGenericAllocation instead of MemoryContextContains
during the PG9.3 merge. This change removes the issue the aforementioned
commit intended to fix.
> Revert "Allocator: Remove 16-byte alignment in GPDB 6"

- doc/mainpage.dox.in
- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_custom_function.sql_in
- tool/docker/base/Dockerfile_postgres_10_Jenkins
This PR adds new helper functions for loading and deleting from a
given table custom functions that can be passed to keras fit/evaluate.
The user passes in the function name along with a valid dill pickled
object. This commit also adds dev-check tests for it.
> DL: Add utility function for custom functions

- src/ports/postgres/modules/dbscan/dbscan.py_in
- src/ports/postgres/modules/dbscan/dbscan.sql_in
- src/ports/postgres/modules/dbscan/test/dbscan.sql_in
The previous dbscan_predict implementation failed on greenplum
if called on a table since the UDFs running on segments cannot
access tables. This implementation creates an output table to
fix this issue.
> DBSCAN: Fix predict on Greenplum

- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_custom_function.setup.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_custom_function.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_model_selection_table.py_in
This PR adds an optional param `object_table` (storing keras custom
function objects) to `load_model_selection_table()`. This object table
(if specified) is added to the summary table named
`<model_selection_table>_summary`, which can be passed to the
fit/evaluate functions.
The new interface is
```
load_model_selection_table(
model_arch_table,
model_selection_table,
model_id_list,
compile_params_list,
fit_params_list,
object_table             -- new optional parameter
)
```
<model_selection_table>_summary:
```
model_arch_table    VARCHAR. Name of the model architecture table containing the model architecture IDs.
object_table        VARCHAR. Name of the object table containing the serialized Python objects for custom loss functions and custom metrics.   -- new column in this summary …
```
> DL: Add object table info in load MST table utility

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
Instead of reading the weights from a table and passing to the
evaluate function, we decided to pass the table directly and
let the evaluate function handle reading in the same query.
> DL: Remove weight passing for multi model evaluate

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_averaging_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_transfer_learning.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: https://issues.apache.org/jira/browse/MADLIB-1441
For MADlib deep_learning module to support custom functions, we have the following functions are affected:
1. madlib_keras_fit()
2. madlib_keras_fit_multiple_model()
3. madlib_keras_evaluate()
Currently the compile_param passed in are like
`optimizer=SGD(lr=0.01, decay=1e-6, nesterov=True), loss='categorical_crossentropy', metrics=['mae']`
For a custom function we would just pass in as follows:
`optimizer=SGD(lr=0.01, decay=1e-6, nesterov=True), loss=custom_fn1, metrics=['mae']` 
Object table definition with a dill object of custom functions is as follows:
|id|name|description|function|
|---|---|---|---|
|1|custom_fn1|test function|\x80026...|
|2|custom_fn2|test function2|\x8ab26...|
For fit_multiple, we want to support multiple …
> DL: Add support for custom loss functions

- src/ports/postgres/modules/graph/apsp.sql_in
- src/ports/postgres/modules/graph/bfs.py_in
- src/ports/postgres/modules/graph/bfs.sql_in
- src/ports/postgres/modules/graph/hits.py_in
- src/ports/postgres/modules/graph/hits.sql_in
- src/ports/postgres/modules/graph/measures.py_in
- src/ports/postgres/modules/graph/measures.sql_in
- src/ports/postgres/modules/graph/pagerank.py_in
- src/ports/postgres/modules/graph/pagerank.sql_in
- src/ports/postgres/modules/graph/sssp.py_in
- src/ports/postgres/modules/graph/sssp.sql_in
- src/ports/postgres/modules/graph/test/apsp.sql_in
- src/ports/postgres/modules/graph/test/bfs.sql_in
- src/ports/postgres/modules/graph/test/hits.sql_in
- src/ports/postgres/modules/graph/test/measures.sql_in
- src/ports/postgres/modules/graph/test/pagerank.sql_in
- src/ports/postgres/modules/graph/test/sssp.sql_in
- src/ports/postgres/modules/graph/test/wcc.sql_in
- src/ports/postgres/modules/graph/wcc.py_in
- src/ports/postgres/modules/graph/wcc.sql_in
JIRA: MADLIB-1444
Graph modules cast the vertex ids to integers in a few spots.
This commit fixes the issue by using bigint type.
> Graph: Fix handling of bigint columns

- doc/mainpage.dox.in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_model_selection_table.py_in
- src/ports/postgres/modules/kmeans/kmeans.sql_in
JIRA: MADLIB-1439
The `load_model_selection_table` function requires the user to manually specify the grid of compile and fit params. Hence, we implement a function called `generate_model_configs` (in the same module) to perform grid/random search.
The user would declare the compile and fit params grid separately as strings enveloping python dictionaries, and the name of the search algorithm (along with any corresponding arguments), and the output format of the new function would be the same as the previous one for better integrability with other MADlib functions related to model training etc. 
This pull request includes the implementation, unit tests (in python and SQL) and documentation for the newly created function.
> DL: Add grid/random search for model selection with `generate_model_configs`

- src/ports/postgres/modules/deep_learning/madlib_keras_automl.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_automl.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_automl.py_in
JIRA: MADLIB-1445
As part of the new AutoML module for Model Selection with Deep Learning, we implement a utility function called `hyperband_schedule` to generate a viewable schedule for hyperband execution. 
This is aimed at users interested in using the hyperband algorithm and wanting to explore a variety of schedules with particular R, eta, or skip_last values, to make an informed decision on the schedule they prefer to use for the actual execution of the algorithm (which will be supported in an AutoML PR coming soon).
> DL: [AutoML] Add utility function `hyperband_schedule` to generate Hyperband schedule for AutoML

- src/ports/postgres/modules/deep_learning/madlib_keras_automl.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_automl.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_automl.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_automl.py_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_model_selection_table.py_in
JIRA: MADLIB-{1447,1448,1449}
We integrate AutoML capabilities in Apache MADlib by introducing a function called `madlib_keras_automl`, which bridges the worlds of setting and running model selection together, and helps automate and accelerate the model selection and training processes end-to-end. The user can declaratively specify the names of their train/val datasets, mst and output tables, model architecture and param grid details, the chosen method name and associated params, and various training details as desired, and our API handles the scheduling and execution components with the algorithm workload info displayed to the user.
The first AutoML algorithm we implement is Hyperband, a state-of-the-art hyperparameter optimization algorithm which speeds up random search with adaptive …
> DL: [AutoML] Add support for 'diagonal' Hyperband optimized for MPP

- src/ports/postgres/modules/deep_learning/madlib_keras_automl.py_in
JIRA: MADLIB-1447
There is a known issue when calling fit multiple model with huge model
weights(JIRA: MADLIB-1414). The fix for that issue was to set
`plan_cache_mode` guc in gpdb6 to `force_generic_plan`. For automl,
since we directly call madlib_keras_fit_multiple_model from the within
the automl function, we need to set the GUC plan_cache_mode when calling
it.
> DL: [AutoML] Set plan_cache_mode when calling fit multiple model

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1427
Currently passing around independent and dependent vars to the
transition function is what takes up most of the time.
As part of this PR, a new fit_multipl_transition function is called that
reads all the rows (for each seg) into the cache(SD) for the very first
hop and for each subsequent hop/iteration, the data is read from the
cache instead of table and cleared out at the final training call. This
helps reduces the time to pass along the data to the transition function.
Since, the data is cached into memory, the memory usage per segment
increases significantly. To avoid this, a new optional param
`use_caching` is added to madlib_keras_fit_multiple_model(), that can be
set to TRUE if the memory on each segment meets the following
calculation:
IND_SZ (indep var size of …
> DL: Implement caching for fit_multiple_model

- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_custom_function.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_averaging_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1452
This commit enables the top_n_accuracy metric. The current parser
cannot use top_n_accuracy(k=3) format because we don't want to
run eval for security reasons. Instead, we add a helper function
so that the user can easily create a custom top_n_accuracy
function.
> DL: Add a helper function to load custom top n accuracy functions

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_automl.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_model_selection.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_custom_function.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_averaging_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras_model_selection_table.py_in
- src/ports/postgres/modules/utilities/utilities.py_in
This commit ensures that any custom function table is cretated in
the madlib schema. This table should be accessible by the admin only,
which means the load_custom_function is only available to admins or
superusers as well.
> DL: Restrict access to the custom functions table

- src/ports/postgres/modules/regress/linear.py_in
Linear regression training results in 2 output tables (**neither are optional**): 
The **primary** output table, that includes the computed coefficients.
A **summary** output table, that contains a single line.
Running the linear regression training in postgresql on an input table which has **more than 2^31 records** within it (even if a grouping column is specified), fails due to an "**integer out of range**" exception.
**The summary table** has a column that stores **the total number of records** involved in the computation. The column's data type is a **singed integer**. However, the total number of records is computed as a **BIGINT**. Therefore, when the total number of records in the input table is beyond the range of a signed integer (i.e., 2^31), an "integer out of range" exception …
> Prevent an "integer out of range" exception in linear regression train

- src/ports/postgres/modules/regress/linear.sql_in
As part of commit b0991965f7d4007d47902afcf7b319a78d766613 , we updated
num_rows_processed column to be of type BIGINT.  This commit makes the
doc changes for that code change
Authored-by: Ekta Khanna <ekhanna@vmware.com>
> regress: Update linear regression docs

- src/ports/postgres/modules/deep_learning/madlib_keras_automl.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_automl_hyperband.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_automl_hyperopt.py_in
Following the principle of encapsulation, AutoML should keep track of its own temporary table names, instead of relying on assumptions about where they will be stored internally to the FitMultipleModel class.
These changes allow it to co-exist with the Model Hopper refactor (but are independent from that PR), and should help make AutoML more robust to any future changes we make inside FitMultipleModel.
> DL: AutoML encapsulation

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_automl_hyperband.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_automl_hyperopt.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_serializer.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
- src/ports/postgres/modules/deep_learning/model_arch_info.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit_multiple.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_iris.setup.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
- src/ports/postgres/modules/internal/db_utils.py_in
- src/ports/postgres/modules/utilities/validate_args.py_in
This is a major refactor of the model hopper parallelism of the deep learning module.
In v1.17, MADlib creates 3 temporary tables to store the model weights while they are being
hopped around and trained:  mst_weights_tbl, weights_to_update_tbl, and model_output_table.
This gives rise to 3 different long-running queries that each involve at least one Redistribute Motion:
the UDA query (which does the actual training), the UPDATE query, and the HOP query.  Most of the time in
madlib_keras_fit_multiple() is spent in a loop over iterations and hops calling the run_training()
function which performs each of these 3 stages, where all of the models circulate between
these 3 temporary tables and get back to where they started after each full iteration.
The overall effect was a lot of unnecessary …
> DL: Model Hopper Refactor

- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
JIRA: MADLIB-1462
Previously when running fit_multiple (with or without validation dataset), we
weren't printing the timing for the evaluate runs. This commit adds code to
print timing for both training evaluate and validation evaluate.
If the user specifies only the training dataset, then the following will be added to the existing output
1. The cumulative time it took for all the msts to run evaluate for the training dataset for that iteration
If the user specifies a validation dataset, then the following will be added to the existing output
1. The cumulative time it took for all the msts to run evaluate for the training dataset for that iteration
2. The cumulative time it took for all the msts to run evaluate for the validation dataset for that iteration
> DL: print timing for evaluate operation in fit multiple

- src/ports/postgres/modules/deep_learning/input_data_preprocessor.py_in
- src/ports/postgres/modules/deep_learning/input_data_preprocessor.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_automl.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_automl_hyperopt.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/model_arch_info.py_in
- src/ports/postgres/modules/deep_learning/predict_input_params.py_in
- src/ports/postgres/modules/deep_learning/test/input_data_preprocessor.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_automl.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_cifar.setup.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit_multiple.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_iris.setup.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_averaging_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_model_selection_e2e.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_multi_io.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_predict.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_predict_byom.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_transfer_learning.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_input_data_preprocessor.py_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
- src/ports/postgres/modules/utilities/utilities.py_in
This commit adds support for multiple dependent and independent variables.
These changes should allow the users to use YOLO v3 and v4 models.
Note that the existing interface with single dependent and single independent
variables still works as expected. The output table formats have changed
slightly to accomodate this new feature. The summary tables store various
fields such as num_classes or dep_vartype as arrays, even if they have single
entries.
The implementation reads up to 5 dependent and 5 independent variables
separately thanks to the new interface. If more variables are passed, they are
packed into bytea arrays. A high number of large variables might cause us to go
over the 1 GB limit of Postgres due to packing.
> DL: Add multiple variable support

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_fit_multiple.sql_in
- src/ports/postgres/modules/deep_learning/test/madlib_keras_iris.setup.sql_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
JIRA: MADLIB-1463
Previously, the calculation of `gpu_mem_fraction` assumed that
num_segments = all_segments which is not always the case. The user can
pass in a distribution rules table to input preprocessor and the data
can be distributed to less segments than the total number of segments on
the cluster.
This commit replaces the get_segments_per_host function call with
a new function `get_data_distribution_per_segment` which returns the actual distribution
of the data instead of returning a list of all the segments. Using this,
we can calculate the correct memory fraction.
> DL: Fix gpu mem fraction calc when data isn't distributed to all segs

- src/ports/postgres/modules/kmeans/test/kmeans.sql_in
The auto kmeans dev check tests were using the incorrect column
for expr_point which caused some flaky tests.
> Kmeans: Fix auto kmeans tests

- CMakeLists.txt
- src/CMakeLists.txt
- src/dbal/BoostIntegration/MathToolkit_impl.hpp
- src/dbal/Reference_proto.hpp
- src/library.ver
- src/modules/lda/lda.cpp
- src/modules/recursive_partitioning/DT_impl.hpp
- src/modules/recursive_partitioning/feature_encoding.cpp
- src/modules/sample/WeightedSample_impl.hpp
- src/modules/stats/wilcoxon_signed_rank_test.cpp
- src/ports/postgres/dbconnector/NativeRandomNumberGenerator_proto.hpp
- src/ports/postgres/dbconnector/NewDelete.cpp
This is an assortment of bug fixes and improvements for our optional C++11 support.
It's mostly only relevant for those who were compiling by passing the -DCXX11 option manually.
Previously, that was the only way to compile with C++11, and it only affected clang (not gcc).
But in addition to fixing some bugs and warnings, this PR also improves the logic in the CMake
configuration files.  Previously if you had too recent a version of boost ( > v1.64) and the -DCXX11
option was not passed, it would just fail.  With the new behavior, it will auto-enable CXX11 support
if the version of Boost requires it.  It could still fail, if the compiler doesn't support C++11, but this
is no worse than the previous behavior.  If the option is passed manually and the detected Boost is
too old, it will …
> Fix some C++11 issues

- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.sql_in
This PR fixes a couple of exception handling bugs in the dl module
JIRA: MADLIB-1467
1. Replaces e.args[0] with e.message
2. Replaces TransAggDetail with UDFDetail in fit multiple
In a future PR, we will consolidate all this code so that there is no duplication and the code is easier to maintain.
> DL: Fix exception handling bugs

- src/ports/postgres/modules/deep_learning/input_data_preprocessor.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_helper.py_in
JIRA: MADLIB-1468
training_preprocessor_dl() function fails with the following error when the
number of images in a buffer is > range for smallint i.e. -32768 to +32767.
```
ERROR: spiexceptions.NumericValueOutOfRange: smallint out of range
```
This commit replaces smallint with INTEGER for the shape column.
Co-authored-by: Nikhil Kak <nkak@vmware.com>
> DL: Update ind/dep var shape to INTEGER instead of smallint

- src/ports/postgres/modules/deep_learning/madlib_keras.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_predict.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
JIRA: MADLIB-1467
We noticed that we run tf operations like `model.fit` on gpu device
using `with tf.device(/gpu:0):`. It turns out that some of the
operations(like passing class_weight as a fit param) may not be fully
supported on gpus. Since we already set `CUDA_VISIBLE_DEVICES` env
variable, we don't explicitly need to use the with clause to force the
operation to be run on gpus. So to fix this issue, this commit removes all
the with clauses so that operations are allowed to run on cpu as well.
Co-authored-by: Ekta Khanna <ekhanna@vmware.com>
> DL: Remove with clause while running tf operations

- src/ports/postgres/modules/convex/mlp_igd.py_in
- src/ports/postgres/modules/convex/test/mlp.sql_in
- src/ports/postgres/modules/convex/utils_regularization.py_in
JIRA: MADLIB-1471
When passing in the weights param as a column in the table, it would
fail with the error `column does not exist`. This column was missed when
calling the step function. If it were passed in as a constant value,
this would work fine. We fixed this by adding the weights column to the
normalized/scaled table.
Additionally, there was a bug in validating the
weights column type, it validated only for integer and float types and
would fail for other numeric types. The intented column type was all
numeric types.
This commit fixes both these bugs and adds tests for
passing in weights as a table column.
Co-authored-by: Ekta Khanna <ekhanna@vmware.com>
> MLP: Fix bug in weights argument

- src/ports/postgres/modules/deep_learning/madlib_keras.sql_in
- src/ports/postgres/modules/deep_learning/model_arch_info.py_in
- src/ports/postgres/modules/deep_learning/test/unit_tests/test_madlib_keras.py_in
get_num_classes function did not work in certain models that end
with activation layers. The regresion was caused by the changes
from the multi-io commit.
> DL: Fix num_class parsing from model architecture

- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_fit_multiple_model.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_validator.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_wrapper.py_in
Here are a few improvements to how we process compile params, so that the code is more robust from a security perspective. 
I haven't found a specific security exploit for these issues, but I wouldn't be surprised if someone with enough time and dedication could find a way to gain admin access via them... especially if there were a minor update to either MADlib's deep learning library or keras which doesn't take into account these potential issues.  (And at the very least, this fixes some odd error messages and crashes that can happen when strange parameters are passed.)
Changes:
1.  Exclude `deserialize`, `serialize`, `get`, and anything starting with `_` from the list of builtin losses and metrics we support.
We were unintentionally allowing users to pass `keras.losses.deserialize`, …
> Strengthen security checks on compile params

- CMakeLists.txt
- src/ports/postgres/dbconnector/NewDelete.cpp
There are some crashes we're seeing related to memory management when the C++11 flag is enabled.  It only happens when compiler optimizations at level O2 or higher are enabled, which makes it very difficult to debug.
Since this is not an essential feature, and currently only works on OSX anyway, in the meantime we will simply disable compiler optimization for that case.
> Avoid using optimization -O2 or higher if C++11 is enabled

- src/ports/postgres/modules/deep_learning/test/madlib_keras_evaluate.sql_in
This was getting divide-by-zero errors whenever the final training
loss or metric from the previous iteration was exactly 0
> Fix flaky keras_evaluate relative-error test

- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.py_in
- src/ports/postgres/modules/deep_learning/madlib_keras_custom_function.sql_in
On running back to back queries for load_top_k_accuracy_function in the
same psql session on GPDB6, if any query fails in between, the very
next query hangs. This commit fixes that issue by moving the with
AOControl clause to where we create the table, rather than updating it
at the function entry level.
Removed top level AOControl from `load_custom_function` too as that is what we internally call from load_top_k_accuracy_function.
> DL: Remove AOcontrol from load_top_k_accuracy fn

- deploy/gppkg/gppkg_spec.yml.in
- deploy/gppkg/madlib.spec.in
- src/madpack/changelist_1.18.0_1.19.0-dev.yaml
- src/madpack/madpack.py
The MODULE_PATHNAME variable is set to an absolute path
during preprocessing. This creates an issue with the gpupgrade
since the database path changes and the old path becomes invalid.
This commit creates a link in the $libdir directory of the
greenplum installation and uses that link to create the MADlib
UDFs.
It fixes an issue with the upgrade scripts as well. The drop
commands are generated using the arguments but including
DEFAULT values breaks the drop function command. The commit
filters them out.
> Build: Fix module pathname for gppkg

- src/ports/postgres/modules/graph/test/wcc.sql_in
- src/ports/postgres/modules/graph/wcc.py_in
WCC had a high number of plpy.execute commands. Since each call
creates a new subtransaction, it was constantly hitting the
overflow limit. This commit merges most of them.
WCC also created and dropped temp tables in each iteration.
This bloats the catalog, so this commit uses a few actual
tables and uses truncate/insert.
> @orhankislal WCC: Optimize subtx count and catalog entry frequency

- src/ports/postgres/modules/svm/svm.py_in
- src/ports/postgres/modules/svm/test/svm.sql_in
- src/ports/postgres/modules/utilities/in_mem_group_control.py_in
The group iteration controller prepares a plan and executes it during
the update phase. For some modules, this plan does not change between
iterations. With this commit, the plan gets saved and reused as needed.
Co-authored-by: Bhuvnesh Chaudhary <bchaudhary@pivotal.io>
> Utilities: Reuse update plan in GroupIterationController 

- doc/example/madlib_pagerank_example.sql
- doc/example/madlib_wcc_example.sql
- src/ports/postgres/modules/dbscan/test/dbscan.sql_in
- src/ports/postgres/modules/graph/graph_utils.py_in
- src/ports/postgres/modules/graph/pagerank.py_in
- src/ports/postgres/modules/graph/pagerank.sql_in
- src/ports/postgres/modules/graph/test/pagerank.sql_in
- src/ports/postgres/modules/graph/test/wcc.sql_in
- src/ports/postgres/modules/graph/wcc.py_in
- src/ports/postgres/modules/graph/wcc.sql_in
- src/ports/postgres/modules/utilities/validate_args.py_in
JIRA: MADLIB-1502, MADLIB-1503
This commit adds support for identifying vertices with multiple columns
for Pagerank and WCC modules. The rest of the graph modules will add the
same functionality in later commits.
The multi column support is done by creating views in which we collect
the given BIGINT columns into a single BIGINT array.
Co-authored-by: Bhuvnesh Chaudhary <bchaudhary@pivotal.io>
> Graph: Add multi column support for Pagerank and WCC

- cmake/LinuxUtils.cmake
- deploy/CMakeLists.txt
- deploy/RPM/CMakeLists.txt
Build System: Support Photon OS
JIRA: MADLIB-1510
Previously the building system only support Centos and Debian OS.
In order to run MADlib on Photon OS, we need the support to build it
with cmake on Photon OS.
Co-authored-by: Jianwen Dong <djianwen@vmware.com>
Co-authored-by: Gaurab Dey <gaurabd@vmware.com>
> Build System: Support Photon OS

- cmake/LinuxUtils.cmake
- deploy/CMakeLists.txt
- deploy/RPM/CMakeLists.txt
JIRA: MADLIB-1510
Creating RPMs on Photon 3 systems missed rpm scripts. This commit
ensures that it is treated like a redhat system and necessary scripts
are included in the metadata.
> Build: Fix photon rpm creation

- src/ports/postgres/modules/mxgboost/madlib_xgboost.py_in
- src/ports/postgres/modules/mxgboost/madlib_xgboost.sql_in
- src/ports/postgres/modules/mxgboost/test/madlib_xgboost.sql_in
- Fix class label verification in predict
Class label is an optional argument for predict but the code checks to
ensure the column exists in the table. This commit fixes the issue and
adds a test to run predict with default values and no optional
parameters.
- Add support for bigint and varchar id col
XGBoost supports non-integer values as id columns (not features) in the
python implementation. This commit alters the surrounding code to
accomodate for such column types and adds/alters tests accordingly.
- Add eval_metrics as a parameter
eval_metrics is used by XGBoost used monitoring the training result and
early stopping. We expose this parameter to the user and parse it to
pass it to the fit function (instead of init).
> XGBoost: Fix class label verification in predict

- src/ports/postgres/modules/graph/sssp.py_in
- src/ports/postgres/modules/graph/test/sssp.sql_in
SSSP checks the iteration counter to identify negative cycles. If a shortest path has the same length as the number of vertices, then the check incorrectly identifies this as a negative cycle. This commit fixes the issue and adds a relevant test.
> SSSP: Fix negative cycle check

- src/ports/postgres/modules/graph/graph_utils.py_in
- src/ports/postgres/modules/graph/test/wcc.sql_in
- src/ports/postgres/modules/graph/wcc.py_in
- src/ports/postgres/modules/graph/wcc.sql_in
WCC creates a large number of subtransactions which may cause system performance degredation in some cases. This cpmmit adds a parameter to limit the number of iterations it runs as well as another one to continue from the incomplete state.
> WCC: Add warm start
